// ============================================================================
// Media Download Center — Tipos Fundamentales
// ============================================================================

// ─── Capacidades del Provider ──────────────────────────────────────────────

export enum ProviderCapability {
  Video = "video",
  Audio = "audio",
  Playlist = "playlist",
  Channel = "channel",
  Subtitles = "subtitles",
  Thumbnail = "thumbnail",
  Metadata = "metadata",
}

// ─── Formatos Soportados ────────────────────────────────────────────────────

export enum VideoFormat {
  MP4 = "mp4",
  MKV = "mkv",
  WEBM = "webm",
  AVI = "avi",
  MOV = "mov",
}

export enum AudioFormat {
  MP3 = "mp3",
  FLAC = "flac",
  AAC = "aac",
  OPUS = "opus",
  OGG = "ogg",
  WAV = "wav",
}

export type MediaFormat = VideoFormat | AudioFormat;

export enum QualityLevel {
  Auto = "auto",
  p144 = "144p",
  p240 = "240p",
  p360 = "360p",
  p480 = "480p",
  p720 = "720p",
  p1080 = "1080p",
  p1440 = "1440p",
  p2160 = "2160p",
  p4320 = "4320p", // 8K
  Custom = "custom",
}

// ─── Estado de Tarea de Descarga ──────────────────────────────────────────

export enum TaskStatus {
  Queued = "queued",
  Running = "running",
  Paused = "paused",
  Cancelled = "cancelled",
  Completed = "completed",
  Failed = "failed",
}

// ─── Modos de Visualización ────────────────────────────────────────────────

export enum WidgetMode {
  Tab = "tab",
  Panel = "panel",
  Floating = "floating",
}

// ─── Información del Proveedor ──────────────────────────────────────────────

export interface ProviderInfo {
  name: string;
  displayName: string;
  icon: string;         // Material Symbol name
  color: string;        // Color hex para acentos
  capabilities: ProviderCapability[];
  supportedVideoFormats: VideoFormat[];
  supportedAudioFormats: AudioFormat[];
  urlPatterns: string[]; // Ej: ["youtube.com", "youtu.be"]
}

// ─── Información del Media ─────────────────────────────────────────────────

export interface MediaInfo {
  url: string;
  provider: string;
  title: string;
  author: string;
  duration: number;       // segundos
  thumbnail: string;      // URL
  webpageUrl: string;
  description?: string;
  uploadDate?: string;
  viewCount?: number;
  likeCount?: number;
  isLive?: boolean;
  formats: FormatInfo[];
  subtitles: SubtitleInfo[];
  chapters?: ChapterInfo[];
}

export interface FormatInfo {
  formatId: string;
  extension: string;
  resolution?: string;
  width?: number;
  height?: number;
  filesize: number;       // bytes
  filesizeApprox: number; // bytes estimados
  bitrate: number;
  audioBitrate?: number;
  videoBitrate?: number;
  hasVideo: boolean;
  hasAudio: boolean;
  fps?: number;
  codec?: string;
  audioCodec?: string;
  formatNote?: string;
}

export interface SubtitleInfo {
  language: string;
  extension: string;
  isAutoGenerated: boolean;
  url?: string;
}

export interface ChapterInfo {
  title: string;
  startTime: number; // segundos
  endTime: number;
}

// ─── Opciones de Descarga ──────────────────────────────────────────────────

export interface DownloadOptions {
  url: string;
  provider?: string;
  format: MediaFormat;
  quality: QualityLevel | string; // string para formato custom de yt-dlp
  outputPath: string;
  filename?: string;
  downloadSubtitles: boolean;
  subtitleLanguages: string[];
  downloadThumbnail: boolean;
  embedThumbnail: boolean;
  embedMetadata: boolean;
  speedLimit?: number;        // KB/s
  concurrentConnections?: number; // Número máximo de conexiones
  customFormat?: string;      // Formato custom de yt-dlp
  extractAudio: boolean;
  audioQuality?: string;      // ej: "192k"
}

// ─── Tarea de Descarga ─────────────────────────────────────────────────────

export interface DownloadTask {
  id: string;
  options: DownloadOptions;
  mediaInfo?: MediaInfo;
  status: TaskStatus;
  progress: DownloadProgress;
  retries: number;
  maxRetries: number;
  error?: string;
  createdAt: number;
  startedAt?: number;
  completedAt?: number;
  filePath?: string;
  fileSize?: number;
}

export interface DownloadProgress {
  percent: number;       // 0-100
  speed: number;         // bytes/s
  eta: number;           // segundos restantes
  downloadedBytes: number;
  totalBytes: number;
  speedFormatted: string;
  etaFormatted: string;
  downloadedFormatted: string;
  totalFormatted: string;
  currentFragment?: number;
  totalFragments?: number;
}

// ─── Historial ─────────────────────────────────────────────────────────────

export interface HistoryEntry {
  id: number;
  task_id: string;
  url: string;
  provider: string;
  title: string;
  author: string;
  format: string;
  quality: string;
  filePath: string;
  fileSize: number;
  duration: number;
  thumbnail?: string;
  status: TaskStatus;
  error?: string;
  isFavorite: boolean;
  createdAt: number;
  completedAt?: number;
}

// ─── Configuración ─────────────────────────────────────────────────────────

export interface AppConfig {
  defaultDownloadPath: string;
  maxConcurrentDownloads: number;
  speedLimit: number;           // 0 = ilimitado
  maxConnections: number;       // por descarga
  autoDownloadThumbnail: boolean;
  autoDownloadSubtitles: boolean;
  autoEmbedThumbnail: boolean;
  autoEmbedMetadata: boolean;
  defaultVideoFormat: VideoFormat;
  defaultAudioFormat: AudioFormat;
  defaultQuality: QualityLevel;
  defaultSubtitleLanguages: string[];
  theme: "dark" | "light";
  widgetMode: WidgetMode;
  checkUpdates: boolean;
  enableNotifications: boolean;
}

// ─── Eventos del Sistema ───────────────────────────────────────────────────

export enum SystemEvent {
  DownloadStarted = "download.started",
  DownloadProgress = "download.progress",
  DownloadCompleted = "download.completed",
  DownloadFailed = "download.failed",
  DownloadCancelled = "download.cancelled",
  DownloadPaused = "download.paused",
  DownloadResumed = "download.resumed",
  QueueChanged = "queue.changed",
  ProviderDetected = "provider.detected",
  Error = "system.error",
}

// ─── Handlers IPC ──────────────────────────────────────────────────────────

export type IpcHandler = (...args: any[]) => any | Promise<any>;

export interface IpcRoute {
  method: string;
  handler: IpcHandler;
  description: string;
}

// ─── Interfaces del Provider ────────────────────────────────────────────────

export interface IProvider {
  readonly info: ProviderInfo;

  /** Detecta si esta URL pertenece a este provider */
  match(url: string): boolean;

  /** Extrae información del media desde la URL */
  getInfo(url: string, options?: Partial<DownloadOptions>): Promise<MediaInfo>;

  /** Prepara los args de yt-dlp para este provider */
  buildDownloadArgs(options: DownloadOptions): string[];
}
